export ZSH="/Users/[usr]/.oh-my-zsh"
export LC_ALL=en_US.UTF-8
TERM=xterm-256color
export POWERLEVEL9K_IGNORE_TERM_COLORS=false
export POWERLEVEL9K_IGNORE_TERM_LANG=false

POWERLEVEL9K_MODE='nerdfont-complete'
ZSH_THEME="powerlevel9k/powerlevel9k"

#CUSTOM PROMPT
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%{%F{red}%}\u250f "
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%{%F{red}%}\u2517%{%F{default}%} $%{%F{default}%} "

#ELEMENTS
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( 'context' 'dir' 'vcs' )
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%{%F{red}%} \u002D '
POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=''

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time)
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '
POWERLEVEL9K_WHITESPACE_BETWEEN_RIGHT_SEGMENTS=''

#DIR
POWERLEVEL9K_ETC_ICON=''
POWERLEVEL9K_FOLDER_ICON=''
POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_DIR_HOME_BACKGROUND=default
POWERLEVEL9K_DIR_HOME_FOREGROUND='green'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND=default
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='green'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=default
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='green'

# TIME
POWERLEVEL9K_TIME_BACKGROUND=default
POWERLEVEL9K_TIME_FOREGROUND='green'
POWERLEVEL9K_TIME_FORMAT='%D{%I:%M:%S %p}'
POWERLEVEL9K_TIME_ICON=''

#VCS
POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_VCS_STAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_UNTRACKED_ICON='\u25CF'
POWERLEVEL9K_VCS_UNSTAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\u2193'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\u2191'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='black'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='blue'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='black'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='black'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='magenta'

plugins=(git iterm2 zsh-autosuggestions zsh-syntax-highlighting)

alias ls='colorls --group-directories-first'

source $ZSH/oh-my-zsh.sh
